import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#262833',
  primaryLight: '#7E8CE0',
  secondary: '#FFAF5F',
  secondaryLight: '#FFA48E',
  warningRed: '#E16060',
  gray: '#F4F4F4',
  grayDarker: '#EDEDED',
}


export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
    topView: {
      flex: 0.3,
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      paddingTop: 80,
    },
      logoImage: {
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
        width: '80%',
        height: '80%',
        resizeMode: 'contain',
      },
    middleView: {
      flex: 0.4,
      justifyContent: 'center',
      alignItems: 'center',
    },
      inputRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        height: 52, 
        width: 280,       
      },
        inputIcon: {
          flex: 0.15,
          borderColor: colors.primaryLight,
        },
        inputLabel: {
          flex: 0.85,
          paddingRight: 8,
        },
        inputText: {
          flex: 0.5,
          paddingLeft: 0,
          fontSize: 15,
          color: 'white',
          borderBottomWidth: 0.3,
          borderColor: colors.primaryLight,
        },
        forgotText: {
          fontSize: 13,
          color: colors.primaryLight,
          textDecorationLine: 'underline',
        },
      bottomView: {
        flex: 0.3,
        flexDirection: 'column',
        justifyContent: 'flex-end',
        paddingLeft:40,
        paddingRight:40,
        paddingBottom: 80,
        alignItems: 'center'
      },
        buttonContainer: {
          justifyContent: 'center',
          alignItems: 'center',
          borderRadius: 100,
          backgroundColor: colors.secondaryLight,
          width: 300,
          height: 60,
          marginBottom: 24,
        },
          buttonText: {
            textAlign: 'center',
            color: colors.primary,
            fontSize: 17,
            fontWeight: '500'
          },
          registerText: {
            fontSize: 13,
            color: colors.primaryLight,
          },
          loginText: {
            fontSize: 17,
            color: colors.secondaryLight,
            textDecorationLine: 'underline',
          },
          termText: {
            fontSize: 13,
            color: colors.primaryLight,
            marginTop: 24,
          },
});

export const FridgeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 20
  },
  topView: {
    flex: 0.06,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 40,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryLight,
  },
    headerBlock: {
      flex: 0.7,
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      paddingLeft: 24,
    },
    headerText: {
      color: colors.primary,
      fontSize: 17,
      fontWeight: '700',
    }, 
    headerButtonBlock: {
      flex: 0.3,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
      paddingRight: 24,
    },
    buttonContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
  bottomView: {
    flex: 0.94,
    justifyContent: 'center',
    alignItems: 'center',
  },
    FridgeListItem: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      backgroundColor: colors.primary,
      height: 104,
      width: 336,
      marginTop: 20,
      marginLeft: 4,
      marginRight: 4,
      borderRadius: 10,
      paddingLeft: 8,
      // card shadow
      shadowColor: 'black',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },  
      FridgeButtonContainer: {
        flex: 0.7,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        borderRadius: 8,
        width: 200,
        height: 60,
        marginLeft: 8,
        marginTop: 16,
      },
      FridgeListSubText: {
        color: colors.primaryLight,
        fontSize: 17,
        fontWeight: '300',
        paddingLeft: 8,
        paddingBottom: 8,
      },  
      FridgeListText: {
        color: colors.secondaryLight,
        fontSize: 24,
        fontWeight: '300',
        paddingLeft: 8,
      },  
      cogButtonContainer: {
        flex: 0.3,
        justifyContent: 'flex-start',
        alignItems: 'flex-end',
        borderRadius: 8,
        width: 40,
        height: 40,
        marginRight: 24,
        marginTop: 16,
      },
  backgroudView: {
    position: 'absolute',
    top: 580,
    justifyContent: 'center',
    alignItems: 'center',
  },
    subText: {
      color: colors.primaryLight,
      fontSize: 13,
      fontWeight: '300',
      paddingBottom: 24,
      width: 280,
      textAlign: 'center',
    },  
    logoImage: {
      width: 80,
      height: 80,
    },
});

export const EditFridgeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'flex-start',
    paddingTop: 20
  },
  topView: {
    flex: 0.1,
    flexDirection: 'column',
    justifyContent: 'center',
    paddingTop: 28,
    paddingLeft: 24,
  },
    headerText: {
      color: colors.primary,
      fontSize: 17,
      fontWeight: '700',
    },
  middleView: {
    flex: 0.7,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginLeft: 24,
    backgroundColor: 'white'
  },     
    inputRow: {
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      width: 320,
      paddingBottom: 14,       
    },    
      subHeaderText: {
        fontSize: 17,
        color: colors.primaryLight,
        paddingBottom: 4,
      },
      inputText: {
        paddingLeft: 0,
        fontSize: 17,
        color: colors.primary,
        borderWidth: 1,
        borderColor: colors.primaryLight,
        height: 40,
        width: 320,
        paddingLeft: 8,
        paddingRight: 8,
      },
      deleteButtonContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 30,
        backgroundColor: colors.warningRed,
        width: 300,
        height: 60,
        marginBottom: 24,
        marginTop: 24,
        marginLeft: 12,
      },
      deleteButtonText: {
        textAlign: 'center',
        color: 'white',
        fontSize: 17,
        fontWeight: '500'
      },
  bottomView: {
    flex: 0.2,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 36,
  },
    buttonContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 30,
      backgroundColor: colors.primary,
      width: 300,
      height: 60,
      marginBottom: 12,
    }, 
    buttonText: {
      textAlign: 'center',
      color: 'white',
      fontSize: 17,
      fontWeight: '500',
    },
    cancelText: {
      fontSize: 17,
      color: colors.primary,
      textDecorationLine: 'underline',
      marginBottom: 24,
    },
});

export const FoodStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 20
  },
  topView: {
    flex: 0.06,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 40,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryLight,
  },
    headerBlock: {
      flex: 0.6,
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
    headerText: {
      color: colors.primary,
      textAlign: 'center',
      fontSize: 17,
      fontWeight: '700',
    }, 
    headerButtonBlock: {
      flex: 0.2,
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    buttonContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
  bottomView: {
    flex: 0.94,
    justifyContent: 'center',
    alignItems: 'center',
  },
    FoodListItem: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      backgroundColor: colors.primary,
      height: 104,
      width: 336,
      marginTop: 20,
      marginLeft: 4,
      marginRight: 4,
      borderRadius: 10,
      paddingLeft: 8,
      // card shadow
      shadowColor: 'black',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    }, 
      foodTypeIconContainer: {
        flex: 0.2,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
        marginTop: 28,
        paddingRight: 4,
      },
      FridgeTextBlock: {
        flex: 0.7,
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        paddingTop:12,
      },      
        FoodTypeText: {
          color: colors.primaryLight,
          fontSize: 13,
          fontWeight: '300',
          paddingLeft: 6,
        }, 
        FoodNameText: {
          color: colors.secondaryLight,
          fontSize: 17,
          fontWeight: '500',
          paddingLeft: 8,
          paddingTop: 2,
        },
        FoodExpText: {
          color: colors.primaryLight,
          fontSize: 17,
          fontWeight: '300',
          paddingLeft: 8,
          paddingTop: 8,
        },
        FoodExpTextExpired: {
          color: colors.warningRed,
          fontSize: 17,
          fontWeight: '500',
          paddingLeft: 8,
          paddingTop: 8,
        },
      cogButtonContainer: {
        flex: 0.2,
        justifyContent: 'center',
        alignItems: 'flex-end',
        borderRadius: 8,
        width: 40,
        height: 40,
        marginRight: 24,
        marginTop: 34,
      },
  backgroudView: {
    position: 'absolute',
    top: 580,
    justifyContent: 'center',
    alignItems: 'center',
  },
    subText: {
      color: colors.primaryLight,
      fontSize: 13,
      fontWeight: '300',
      paddingBottom: 24,
      width: 280,
      textAlign: 'center',
    },  
    logoImage: {
      width: 80,
      height: 80,
    },
});

export const EditFoodStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'flex-start',
    paddingTop: 20
  },
  topView: {
    flex: 0.1,
    flexDirection: 'column',
    justifyContent: 'center',
    paddingTop: 28,
    paddingLeft: 24,
  },
    inputLabel: {
      paddingLeft: 5,
      justifyContent: 'flex-start',
      textAlign: 'left',
      fontSize: 24,
      color: '#E5FFB9',
      paddingTop: 20,
      paddingBottom: 40,
    },
    headerText: {
      color: colors.primary,
      fontSize: 17,
      fontWeight: '700',
    },
  middleView: {
    flex: 0.7,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginLeft: 24,
    backgroundColor: 'white'
  },     
    inputRow: {
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      width: 320,
      paddingBottom: 32,       
    },
    twoElementsRow: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      width: 320,
      paddingBottom: 14,       
    },   
      qtyBlock: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        width: 140,
      },
        qtyEdit: {
          flexDirection: 'row',
          alignItems: 'center',
          height: 40,
          width: 140,
        },       
          qtyButton: {
            flex: 0.35,
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: 10,
            height: 40,
            marginLeft: 2,
            marginRight: 2,
          },
          qtyText: {
            flex: 0.3,
            textAlign: 'center',
            paddingLeft: 0,
            fontSize: 17,
            color: colors.primary,
            borderRadius: 5,
            borderWidth: 1,
            borderColor: colors.primaryLight,
            height: 36,
            paddingLeft: 8,
            paddingRight: 8,
          },
    expBlock: {
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      width: 140,
      marginLeft: 48,
    },
      expInput: {
        textAlign: 'center',
        paddingLeft: 0,
        color: colors.primary,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: colors.primaryLight,
        height: 36,
      },
      datePickerBlock: {
        alignItems: 'center',
        width: 128,
        height: 36,
        paddingLeft: 8,
        paddingRight: 8,
      },
    subHeaderText: {
      fontSize: 17,
      color: colors.primaryLight,
      paddingBottom: 4,
    },
    inputText: {
      paddingLeft: 0,
      fontSize: 17,
      color: colors.primary,
      borderWidth: 1,
      borderColor: colors.primaryLight,
      height: 40,
      width: 320,
      paddingLeft: 8,
    },
      typePickerBlock: {
        alignItems: 'center',
        paddingLeft: 0,
        color: colors.primary,
        borderWidth: 1,
        borderRadius: 10,
        borderColor: colors.primaryLight,
        width: 320,
        paddingLeft: 8,
        paddingRight: 8,
      },
      typePickerItem: {
        fontSize: 17,
        color: colors.primary,
        height: 100,
        width: 324,
        fontWeight: '500',
        textDecorationColor: 'white',
      },
      deleteButtonContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 30,
        backgroundColor: colors.warningRed,
        width: 300,
        height: 60,
        marginBottom: 24,
        marginTop: 24,
        marginLeft: 12,
      },
      deleteButtonText: {
        textAlign: 'center',
        color: 'white',
        fontSize: 17,
        fontWeight: '500'
      },

  bottomView: {
    flex: 0.2,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 36,
  },
    buttonContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 30,
      backgroundColor: colors.primary,
      width: 300,
      height: 60,
      marginBottom: 12,
    }, 
    buttonText: {
      textAlign: 'center',
      color: 'white',
      fontSize: 17,
      fontWeight: '500',
    },
    cancelText: {
      fontSize: 17,
      color: colors.primary,
      textDecorationLine: 'underline',
      marginBottom: 24,
    },
});

export const RoutineStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 20
  },
  backgroudView: {
    position: 'absolute',
    top: 580,
    justifyContent: 'center',
    alignItems: 'center',
  },
    subText: {
      color: colors.primaryLight,
      fontSize: 13,
      fontWeight: '300',
      paddingBottom: 24,
      width: 280,
      textAlign: 'center',
    },  
    logoImage: {
      width: 80,
      height: 80,
    },
    topView: {
      flex: 0.06,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 40,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.primaryLight,
    },
      headerBlock: {
        flex: 0.7,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        paddingLeft: 24,
      },
      headerText: {
        color: colors.primary,
        fontSize: 17,
        fontWeight: '700',
      }, 
      headerButtonBlock: {
        flex: 0.3,
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        paddingRight: 24,
      },
      buttonContainer: {
        justifyContent: 'center',
        alignItems: 'center',
      },
});